# Generated by Django 3.2.4 on 2024-02-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=320),
        ),
    ]
