# Generated by Django 3.2.4 on 2024-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240221_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
