# Generated by Django 3.2.4 on 2024-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_marked_imagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='generate_videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='transfer_videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
